### PR TITLE
Feature/logo

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Love it! :)

**Comment by 3lvis** [comment]
Not a big fan of the stacked rounded corners but it's a great initiative!

**Comment by 3lvis** [comment]
Maybe we can go for yellow instead of red to sort of match up with the current demo. Also might be better if every slice has a different color instead of shades of the same.

What about this ones:

screen shot 2015-05-12 at 9 50 01 pm

What do you think @thuygianguyen?

**Comment by zenangst** [comment]
We (me and @vadymmarkov) started playing around with yellow at the beginning but the "illustration" kinda go lost with the lack of contrast against white, hence going with a different color.
We went with green because it reminded us of an onion which has many layers :sunglasses:

**Comment by vadymmarkov** [comment]
We discussed with @zenangst and agreed that it looks better with shades of the same color, like we have in Form. So I like the current version of logo. But it really depends on colors. Maybe something within palette suggested by @3lvis could work too, with some shade of yellow/orange at the top that makes contrast with "illustration". Just need to see and compare.

**Comment by zenangst** [comment]
One risky thing with going with yellow/orange is that it could end up looking like HomeKit, but we should play around with it some more :)

**Comment by 3lvis** [comment]
>We discussed with @zenangst and agreed that it looks better with shades of the same color, like we have in Form.

— @vadymmarkov 

Form doesn't have shades of the same color, it has 3 different ones

logo-v6

**Comment by 3lvis** [comment]
>One risky thing with going with yellow/orange is that it could end up looking like HomeKit, but we should play around with it some more :)

— @zenangst 

I'm my opinion the risk is in using the stacked rounded corners, we shouldn't have gone in that direction on the first place.

**Comment by zenangst** [comment]
@3lvis that is true but I like how they look in combination to one another. Going full anarchy and having all of them look different feels weird to me.

**Comment by 3lvis** [comment]
@zenangst I like Thuy's idea of having a common theme, but I don't agree that this is the best way.

We could do "breakfast" theme => https://dribbble.com/shots/1528018-The-PBJ-Family?list=searches&tag=icon_family&offset=13

"Lunchbox" theme => https://dribbble.com/shots/1518928-Lunchbox-Crew

"Cities" theme => https://dribbble.com/shots/1075245-City-Icons-for-Offscreen-Magazine-5?list=searches&tag=cities&offset=12

Or anything else that's original.

**Comment by zenangst** [comment]
I'm getting a deja vu that we already had this discussion before and a sense of derailing is brewing in the air. Don't get me wrong, nothing is set in stone or is no longer allowed to discuss but instead of discussing a completely new "art"-direction for all things, could we respect the pull request and focus on what it's really about?

Seems like both @vadymmarkov and @RamonGilabert liked the icon, anyone else care to weight in? @hyperoslo/ios @hyperoslo/design

**Comment by zenangst** [comment]
Pushed an update icon that, for me, made more sense.

logo_v2

**Comment by jgorset** [comment]
I like it, but I think a stack of icons on top of a stack is too much. It confuses my brains! How does it look when the icon isn't a stack?

**Comment by zenangst** [comment]
@jgorset good point ;) stack inception might flip a switch in ones brain and cause seizures, I'll give it another go! :sunglasses:

**Comment by vadymmarkov** [comment]
Agree that we could try the icon without this stack inception, but anyway, I like it. As for our icon style, I have a feeling that stack with rounded corners is something "reserved" by Apple, but it's not very critical. If there are many of us who'd like to discuss it one more time in more detail, we could do it somewhere else, but not in this issue.

**Comment by 3lvis** [comment]
The green one is not going to look very well in the README next to the animated gif, would you mind changing it to something like this?

ffdc3028-f8f0-11e4-89e6-4f4b4c601b9b

**Comment by zenangst** [comment]
Updated the icon, what do you guys think?

logo_v3

**Comment by RamonGilabert** [comment]
Right, with the gift that we currently have in the pod, I think this is the best fit, and also I like now this one better than the stack, good point @jgorset!

**Comment by vadymmarkov** [comment]
Like the new one. I think it's the best fit now. Any other thoughts or we can merge it?

**Comment by zenangst** [comment]
@vadymmarkov go ahead ;)

**Comment by 3lvis** [comment]
Looks good :clap:

**Pull request merged**
