### PR TITLE
Move demo to separate project

### PR DESCRIPTION
**Pull request by vadymmarkov**

### CODE REVIEW

**Comment by 3lvis** [comment]
Can we go for `Tutorial` instead of `Basic`?

**Comment by vadymmarkov** [comment]
@3lvis I'm just wandering what the name should we choose for the second demo (with assets from Thuy) if this one is `Tutorial`. Maybe something like `MagicMove`?

**Comment by 3lvis** [comment]
I guess we only need one Tutorial, the other demos shouldn't be Tutorials too.

**Comment by vadymmarkov** [comment]
@3lvis Ok, let it be Tutorial :smile:

**Comment by 3lvis** [comment]
\o/

**Pull request merged**
