### PR TITLE
Add pod try to improve example on running demos

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by richardoti** [comment]
screen shot 2015-07-08 at 00 30 39
Is there any way to remove ```Pod.xcworkspace``` from menu? If yes, I think, it would be better not to include it in ```pod try``` :smile:

**Comment by 3lvis** [comment]
@richardoti It's an automated process, but you can make a PR here:

https://github.com/CocoaPods/cocoapods-try

**Comment by kostiakoval** [comment]
Yes you can remove it. 
Create a `Example` folder and put your demos there 

That is happening because you have structured the pod in different way. 
run `pod lib create` - this will make you a default pod structure
docs here http://guides.cocoapods.org/making/using-pod-lib-create.html

**Comment by vadymmarkov** [comment]
I've made an issue for it https://github.com/hyperoslo/Presentation/issues/61. Thanks guys, I think we could merge it.

**Pull request merged**
